use_frameworks!

platform :ios, '8.0'

target 'KLToolsLibrary_Example' do
  pod 'KLToolsLibrary', :path => '../'

  target 'KLToolsLibrary_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
